server:
  port: 9097

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micros_db
    username: N_Spark
    password: "{cipher}bbfb93284de74a917587f8de4ccc1b1fa5daf006b6700126702a430f808bef89"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true

info:
  app:
    name: "Food-service"
    description: "This is Food service.Ready to serve users.This configuration is located in config server."
    version: "1.0V Production"

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

  instance:
    hostname: localhost
    prefer-ip-address: true
