server.port=9091
spring.application.name=restaurant-service

#Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=*
management.info.env.enabled=true